# Generated by Django 5.1.5 on 2025-01-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoration',
            name='decoration_image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_image',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='photo_url',
            field=models.FileField(upload_to='images/'),
        ),
    ]
