# Generated by Django 5.1.5 on 2025-01-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_halls_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
