# Generated by Django 5.1.5 on 2025-01-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_bookings_event_id_delete_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='decoration_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='event_status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='bookings',
            name='food_value',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
