# Generated by Django 5.1.5 on 2025-01-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bookings_decoration_value_bookings_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='no_of_persons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
